### ISSUE TITLE
Overhaul Website/ Pages

### ISSUE THREAD

**Issue by nplhse** [nplhse/cois#1311]
**Is your feature request related to a problem? Please describe.**
The current implementation of the Pages and the whole Website stuff is kind of messy, so this really should be changed! 

**Describe the solution you'd like**
First there should be a real "HomepageController" that connects the different parts (e.g. the upcoming blog, the pages, etc.) with the help of Netgen layouts to be more flexible. Also the special Pages should be moved to separate controllers to apply special templates to them too (e.g. link to the user profiles of the board members on the terms, or include the cookie consent in a better way). And last but not least a special FAQ/ Help page should be considered.

**ToDo List**
- [x] Add HomePage Controller to link up the different parts
- [x] Move special Pages to own Controllers (Terms, Imprint, Privacy& Contact)
- [ ] #1346
- [x] Move the visibility of a Page to a new field on the entity to separate it form the special pages.
- [x] ~~Add custom Pages to the "main menu" in the top or to a "sidebar menu" on all pages? Don't know what's better...~~
- [ ] #725
