### ISSUE TITLE
Re-Structure all Data

### ISSUE THREAD

**Issue by nplhse** [nplhse/cois#1312]
**Is your feature request related to a problem? Please describe.**
Currently the users can only view and filter the Allocations which is just a tiny bit of data. It should be moved to a new "Data" section that also contains Hospitals, Areas, Indication Codes, Infections, etc. with their respective informations. This would make much more sense...

**Describe the solution you'd like**
A new section of the application is to be created with a sidebar (on the left?) that lists all the different data types that are available. At first this would just be the Hospitals, Areas and Allocations. As more and more parts of the Allocations get moved into their own objects (see #1057) they also get added here. All of this features should be moved to a general implementation of a special DataTable with the usual filters (see what currently can be done with Allocations). 

**To-Do List:**

- [ ] Create new "Data" section
- [ ] Move Hospitals to new "Data" section
- [ ] Move Areas to "Data" section (see old admin backend)
- [ ] Move Allocations to "Data" section
- [ ] Add new ValueObjects as they are created...
